site:
  title: Demonstration of Antora with Prism
  start_page: demo-process-site::index.adoc

content:
  sources:
    - url: .
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
    - '@antora/collector-extension'
    - ./post-process-html.js
